services:
  - type: web
    name: couchdb
    env: docker
    plan: starter
    dockerfilePath: Dockerfile
    envVars:
      - key: COUCHDB_USER
        value: clev
      - key: COUCHDB_PASSWORD
        value: Production_1
    autoDeploy: true

